# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-09 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=250)),
                ('image', models.ImageField(default=None, upload_to='static/assets/question_images')),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
