# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-12 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decode', '0002_auto_20160710_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='answer',
        ),
    ]
