# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-12 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decode', '0003_remove_level_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='answer',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
