# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-14 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decode', '0004_level_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='static/assets/level_images/'),
        ),
    ]
