# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-10 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='answer',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='level',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=b''),
        ),
    ]
