# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-09 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160709_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='anonymau5', max_length=32, unique=True, verbose_name='username'),
        ),
    ]
