# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-10 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20160709_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='address',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='current_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='decode.Level'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='static/assets/user_images/'),
        ),
    ]
