# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-10 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decode', '__first__'),
        ('accounts', '0008_auto_20160710_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='current_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decode.Level'),
        ),
    ]
