# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-12 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20160712_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='address',
        ),
        migrations.AddField(
            model_name='userdata',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='current_level',
            field=models.IntegerField(default=1),
        ),
    ]
