# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-12 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decode', '0004_level_answer'),
        ('accounts', '0013_auto_20160712_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='level', to='decode.Level'),
        ),
    ]
