# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-12 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userdata_user_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='user_level',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='current_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='level', to='decode.Level'),
        ),
    ]
