# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-13 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20160712_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='current_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='decode.Level'),
        ),
    ]
