# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-13 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20160713_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='current_level_time',
            field=models.DateTimeField(),
        ),
    ]
