# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-13 01:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20160713_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='current_level_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 13, 1, 55, 15, 573800)),
        ),
    ]
