# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-13 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20160713_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='current_level_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
