# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-14 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20160713_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='institute',
            field=models.TextField(default='', max_length=75, null=True),
        ),
    ]
