# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-15 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20160714_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
