# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-07-18 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20160715_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/static/assets/user_images/default.png', upload_to='/static/assets/user_images/'),
        ),
    ]
